### ISSUE TITLE
data loading notebook error

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#151]
Maybe the url changed?

```
ubuntu@ip-172-31-37-12:~/scVI/docs/notebooks$ make data_loading.pdf
jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 data_loading.ipynb;
[NbConvertApp] Converting notebook data_loading.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting 'data_loading.ipynb'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 286, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# Loading a local dataset 
local_ann_dataset = AnnDataset("TM_droplet_mat.h5ad", 
                               save_path = 'data/') 
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-9588bf44b31f> in <module>()
      1 # Loading a local dataset
      2 local_ann_dataset = AnnDataset("TM_droplet_mat.h5ad", 
----> 3                                save_path = 'data/') 

~/scVI/scvi/dataset/anndata.py in __init__(self, filename, save_path, url, new_n_genes, subset_genes)
     35         self.url = url
     36 
---> 37         data, gene_names = self.download_and_preprocess()
     38 
     39         super(AnnDataset, self).__init__(*GeneExpressionDataset.get_attributes_from_matrix(data),

~/scVI/scvi/dataset/dataset.py in download_and_preprocess(self)
     50 
     51     def download_and_preprocess(self):
---> 52         self.download()
     53         return self.preprocess()
     54 

~/scVI/scvi/dataset/dataset.py in download(self)
    139                 GeneExpressionDataset._download(url, self.save_path, download_name)
    140         elif hasattr(self, 'url') and hasattr(self, 'download_name'):
--> 141             GeneExpressionDataset._download(self.url, self.save_path, self.download_name)
    142 
    143     @staticmethod

~/scVI/scvi/dataset/dataset.py in _download(url, save_path, download_name)
    146             print("File %s already downloaded" % (save_path + download_name))
    147             return
--> 148         r = urllib.request.urlopen(url)
    149         print("Downloading file at %s" % save_path + download_name)
    150 

~/anaconda3/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

~/anaconda3/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    515                 req.data = data
    516 
--> 517         req.timeout = timeout
    518         protocol = req.type
    519 

AttributeError: 'NoneType' object has no attribute 'timeout'
AttributeError: 'NoneType' object has no attribute 'timeout'
```

**Comment by imyiningliu** [comment]
I think for `AnnData`, we only support loading local files (discussed [here](https://github.com/YosefLab/scVI/issues/48) :P )

**Comment by jeff-regier** [comment]
Got it. But we should make sure the notebook runs end-to-end without errors.

How about in the notebook downloading the AnnData file then (and unzipping it, if neceesary) before trying to load it? Probably using `urllib` would be best since it's installed by default. e.g.

```
import urllib.request
url = "https://s3.amazonaws.com/czbiohub-tabula-muris/TabulaMuris.h5ad.zip"
response = urllib.request.urlopen(url)
```

(Is that url wrong? ... I'm getting an error right now.)

**Comment by imyiningliu** [comment]
I think it's the correct url because it's the same url as listed in their [GitHub page](https://github.com/czi-hca-comp-tools/easy-data/blob/master/datasets/tabula_muris.md), but the link is broken.

**Comment by jeff-regier** [comment]
@jamestwebber  Do you happen to know if the `TabulaMuris.h5ad.zip` has a new url? Seems like the old one is no longer working.

**Comment by jamestwebber** [comment]
Apologies, the GitHub is out of date and I'll fix it. I was updating/adding to the files there and I realized that the zip was really not saving us anything, so they're uncompressed now. The address should just be `TabulaMuris.h5ad`

**Comment by jeff-regier** [comment]
https://s3.amazonaws.com/czbiohub-tabula-muris/TM_droplet_mat.h5ad works for me.

Thanks James!
