### ISSUE TITLE
make notebooks -- without errors

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#166]
Looks like `make notebooks` throws an error after the last PR.

```
jeff@dean ~/git/scVI $ make notebooks
make -C docs/notebooks
make[1]: Entering directory '/home/jeff/git/scVI/docs/notebooks'
jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 annotation.ipynb;
[NbConvertApp] Converting notebook annotation.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting 'annotation.ipynb'
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 286, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
from scvi.dataset import CortexDataset
from scvi.models import SCANVI, VAE
from scvi.inference import JointSemiSupervisedTrainer
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3f0a2cc69b82> in <module>()
----> 1 from scvi.dataset import CortexDataset
      2 from scvi.models import SCANVI, VAE
      3 from scvi.inference import JointSemiSupervisedTrainer

ModuleNotFoundError: No module named 'scvi'
ModuleNotFoundError: No module named 'scvi'

Makefile:7: recipe for target 'annotation.pdf' failed
make[1]: *** [annotation.pdf] Error 1
make[1]: Leaving directory '/home/jeff/git/scVI/docs/notebooks'
Makefile:94: recipe for target 'notebooks' failed
make: *** [notebooks] Error 2
```

**Comment by jeff-regier** [comment]
Oh, I see the issue...it's the `cd` command in the annotation notebook. We can't count on the user having scVI installed in `~/scVI`.

**Comment by Edouard360** [comment]
Ah yes that's true sorry about that I kept changing it ...

**Comment by jeff-regier** [comment]
Just replacing it with `cd ../..` seems to fix that one, but it reveals some other errors. @Edouard360 Would you make sure `make notebooks` runs wo errors?

**Comment by jeff-regier** [comment]
I'm still getting an error. 

```
jeff@dean ~/git/scVI $ make notebooks
make type= -C docs/notebooks 
make[1]: Entering directory '/home/jeff/git/scVI/docs/notebooks'
jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 annotation.ipynb;
[NbConvertApp] Converting notebook annotation.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 5532 bytes to annotation.nbconvert.ipynb
jupyter nbconvert --to  annotation.ipynb;
[NbConvertApp] ERROR | Error importing annotation.ipynb
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/base.py", line 104, in get_exporter
    return import_item(name)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'annotation'
Traceback (most recent call last):
  File "/home/jeff/miniconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 482, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/base.py", line 110, in get_exporter
    % (name, ', '.join(get_export_names())))
ValueError: Unknown exporter "annotation.ipynb", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
Makefile:9: recipe for target 'annotation.' failed
make[1]: *** [annotation.] Error 1
make[1]: Leaving directory '/home/jeff/git/scVI/docs/notebooks'
Makefile:94: recipe for target 'notebooks' failed
make: *** [notebooks] Error 2
```

**Comment by Edouard360** [comment]
Ok I'll solve this

**Comment by jeff-regier** [comment]
Also getting
```
jeff@dean ~/git/scVI $ make notebooks
make type= -C docs/notebooks 
make[1]: Entering directory '/home/jeff/git/scVI/docs/notebooks'
jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 annotation.ipynb;
[NbConvertApp] Converting notebook annotation.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 5536 bytes to annotation.nbconvert.ipynb
jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 basic_tutorial.ipynb;
[NbConvertApp] Converting notebook basic_tutorial.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 352900 bytes to basic_tutorial.nbconvert.ipynb
jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 scRNA_and_smFISH.ipynb;
[NbConvertApp] Converting notebook scRNA_and_smFISH.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting 'scRNA_and_smFISH.ipynb'
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/jeff/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 286, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
infer.show_t_sne(None, color_by='labels', latent=t_sne_fish, labels =labels_fish[idx_t_sne_fish].ravel())
infer.show_t_sne(None, color_by='scalar', save_name="", latent=t_sne_fish, batch_indices=None,
                        labels=expected_frequencies_fish[idx_t_sne_fish, idx_astro])
------------------

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-28-3502cd031e06> in <module>()
----> 1 infer.show_t_sne(None, color_by='labels', latent=t_sne_fish, labels =labels_fish[idx_t_sne_fish].ravel())
      2 infer.show_t_sne(None, color_by='scalar', save_name="", latent=t_sne_fish, batch_indices=None,
      3                         labels=expected_frequencies_fish[idx_t_sne_fish, idx_astro])

NameError: name 'infer' is not defined
NameError: name 'infer' is not defined

Makefile:9: recipe for target 'scRNA_and_smFISH.' failed
make[1]: *** [scRNA_and_smFISH.] Error 1
make[1]: Leaving directory '/home/jeff/git/scVI/docs/notebooks'
Makefile:94: recipe for target 'notebooks' failed
make: *** [notebooks] Error 2
```
