### ISSUE TITLE
autotune : make specific advanced_tutorial notebook

### ISSUE THREAD

**Issue by gabmis** [YosefLab/scVI#333]
cf. issue title
also, mention MongoDb is a requirement for the parallel version.

**Comment by jeff-regier** [comment]
We might also want to add the ``pymongo``  package to `requirements.txt`, `setup.py`, and our conda recipe so that it gets installed along with the rest of the dependencies.

**Comment by gabmis** [comment]
I believe pymongo is already a hyperopt requirement

**Comment by by-young** [comment]
sorry to disturb you again. when I follow the guidance of the tutorial notebook(Basic scVI Tutorial), the error happens.

I run the command:
best_trainer, trials = auto_tune_scvi_model(
    gene_dataset=gene_dataset,
    parallel=True,
    exp_key="cortex_dataset",
    train_func_specific_kwargs={'n_epochs':n_epochs},
    max_evals=max_evals,
)

error:
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/public/home/yekai/soft/miniconda3/envs/deeplearning/lib/python3.6/site-packages/scvi-0.3.0-py3.6.egg/scvi/inference/autotune.py", line 358, in auto_tune_scvi_model
    multiple_hosts=multiple_hosts,
  File "/public/home/yekai/soft/miniconda3/envs/deeplearning/lib/python3.6/site-packages/scvi-0.3.0-py3.6.egg/scvi/inference/autotune.py", line 492, in _auto_tune_parallel
    stdout=mongo_logfile,
  File "/public/home/yekai/soft/miniconda3/envs/deeplearning/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/public/home/yekai/soft/miniconda3/envs/deeplearning/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'mongod'

**Comment by by-young** [comment]
I am not sure weather the MongDB is at your service and i cannot access to it or not, or any other reason that course the error above.
