### ISSUE TITLE
hyperopt notebook space raises issues

### ISSUE THREAD

**Issue by PierreBoyeau** [YosefLab/scVI#447]
Hi

I started performing hyperoptimization based on the example provided in the autotune notebook
I got the following exception raised after 20 evals.
```
Traceback (most recent call last):
  File "autokiller.py", line 112, in <module>
    parallel=False,
  File "/home/ubuntu/scVI/scvi/inference/autotune.py", line 371, in auto_tune_scvi_model
    trials=trials,
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/fmin.py", line 407, in fmin
    rval.exhaust()
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/fmin.py", line 211, in run
    self.rstate.randint(2 ** 31 - 1))
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/tpe.py", line 900, in suggest
    print_node_on_error=False)
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/scvi/lib/python3.7/site-packages/hyperopt/tpe.py", line 465, in adaptive_parzen_normal
    assert prior_sigma > 0
AssertionError
```

I am pretty sure this is because of the parameter space `"lr": hp.uniform("lr", 0.001, 0.0001)` : that appears in the notebook
The lowest value should appear before the highest, and we might prefer a logspace instead

**Comment by gabmis** [comment]
@PierreBoyeau have changes made in #448 fixed this for you? If so, please close this issue

**Comment by PierreBoyeau** [comment]
Yes thanks!
