### ISSUE TITLE
TypeError in louvain (harmonization notebook)

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#574]
Hi,

When I try to perform harmonization per your tutorial, everything was fine until I reached the clustering step below. Could you kindly help me address the issue? Thanks

###############################
>>> sc.tl.louvain(adata_latent, partition_type=louvain.ModularityVertexPartition, use_weights=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\tools\_louvain.py", line 162, in louvain
    categories=natsorted(np.unique(groups).astype('U')),
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\arrays\categorical.py", line 385, in __init__
    codes = _get_codes_for_values(values, dtype.categories)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\arrays\categorical.py", line 2576, in _get_codes_for_values
    t.map_locations(cats)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1403, in pandas._libs.hashtable.StringHashTable.map_locations
TypeError: Expected unicode, got numpy.str_

########################################

**Comment by adamgayoso** [comment]
Which version of scanpy do you have? The notebooks are tested so this is likely a version issue. I recommend upgrading your scanpy installation if it's older.

**Comment by pchiang5** [comment]
I used the version below, which shall be the latest.

scanpy                    1.4.4.post1                py_1    bioconda

**Comment by adamgayoso** [comment]
It's hard for me to diagnose because the notebooks are reproducible and tested often. You should consider upgrading your pandas, numpy, scanpy (now past 1.4.5), and louvain.

**Comment by pchiang5** [comment]
Turned out the culprit was pandas==1.0.0. The problem was solved with pandas==0.25.3. Thanks

**Comment by adamgayoso** [comment]
Thanks for letting us know @pchiang5 !
