### ISSUE TITLE
TypeError with auto_tune_scvi_model() 

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#610]
I performed the hypermeter search with the following code:

`
import logging
logger = logging.getLogger("scvi.inference.autotune")
logger.setLevel(logging.WARNING) #progress bar
logger.setLevel(logging.INFO) # will show global logs including the number of jobs done.
logger.setLevel(logging.DEBUG) #will show detailed logs for each training (e.g the parameters tested).

from hyperopt import hp
from scvi.inference.autotune import auto_tune_scvi_model

space = {
    "model_tunable_kwargs": {"dropout_rate": hp.choice("dropout_rate", [0.1, 0.3])}, 
	"model_tunable_kwargs": {"n_layers": hp.choice("n_layers", [2, 3, 4])},
    "train_func_tunable_kwargs": {"lr": hp.choice("lr", [0.0001, 0.001])},
	"model_tunable_kwargs": {"n_hidden": hp.choice("n_hidden", [64, 128, 256])}, 
	"model_tunable_kwargs": {"n_latent": hp.choice("n_latent", [6, 10, 20])},
	"model_tunable_kwargs": {"reconstruction_loss": hp.choice("reconstruction_loss", [“zinb”, “nb”])},
}

test_mode = False

def if_not_test_else(x, y):
    if not test_mode:
        return x
    else:
        return y

max_evals = if_not_test_else(100, 1)
fmin_timeout = if_not_test_else(300, 10)
reserve_timeout = if_not_test_else(180, 5)
n_epochs = if_not_test_else(400, 1)
best_trainer, trials = auto_tune_scvi_model(
    gene_dataset=all_dataset,
	use_batches=True,
    metric_name="entropy_batch_mixing",
    posterior_name="train_set",
    parallel=False,
	space=space,
    exp_key="pbmc_entropy_batch_mixing",
    train_func_specific_kwargs={"n_epochs": n_epochs},
    max_evals=max_evals,
    trainer_specific_kwargs={
        "early_stopping_kwargs": {
            "early_stopping_metric": "entropy_batch_mixing",
            "save_best_state_metric": "entropy_batch_mixing",
            "patience": 20,
            "threshold": 0,
            "reduce_lr_on_plateau": True,
            "lr_patience": 10,
            "lr_factor": 0.2,
        }
	},
    reserve_timeout=reserve_timeout,
    fmin_timeout=fmin_timeout,
)
`
However, it came back with the following error. Was there something wrong with my codes?  Thanks

> [2020-03-05 16:54:56,687] INFO - scvi.inference.autotune.all | Starting experiment: pbmc_entropy_batch_mixing
[2020-03-05 16:54:56,688] INFO - scvi.inference.autotune.all | Fixed parameters:
model:
{}
trainer:
{'early_stopping_kwargs': {'early_stopping_metric': 'entropy_batch_mixing', 'save_best_state_metric': 'entropy_batch_mixing', 'patience': 20, 'threshold': 0, 'reduce_lr_on_plateau': True, 'lr_patience': 10, 'lr_factor': 0.2}}
train method:
{'n_epochs': 400}
[2020-03-05 16:54:56,690] INFO - scvi.inference.autotune.all | Starting sequential hyperoptimization
  0%|                                                                                                   | 0/100 [00:00<?, ?it/s, best loss: ?][2020-03-05 16:54:56,704] INFO - scvi.inference.autotune.all | Parameters being tested:
model:
{'reconstruction_loss': 'zinb'}
trainer:
{'early_stopping_kwargs': {'early_stopping_metric': 'entropy_batch_mixing', 'save_best_state_metric': 'entropy_batch_mixing', 'patience': 20, 'threshold': 0, 'reduce_lr_on_plateau': True, 'lr_patience': 10, 'lr_factor': 0.2}, 'use_cuda': True, 'show_progbar': False, 'frequency': 1}
train method:
{'lr': 0.0001, 'n_epochs': 400}
[2020-03-05 16:54:56,706] DEBUG - scvi.inference.autotune.all | Instantiating model
[2020-03-05 16:54:56,800] DEBUG - scvi.inference.autotune.all | Instantiating trainer
[2020-03-05 16:54:56,868] DEBUG - scvi.inference.autotune.all | Starting training
[2020-03-05 16:58:27,801] ERROR - scvi.inference.autotune.all | Caught ("unsupported operand type(s) for -: 'NoneType' and 'float'",) in _objective_function, starting cleanup.
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 165, in decorated
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 1237, in _objective_function
    trainer.train(**train_func_tunable_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 182, in train
    if not self.on_epoch_end():
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 230, in on_epoch_end
    self.history[save_best_state_metric + "_" + on][-1]
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 519, in update_state
    self.mode_save_state == "max" and scalar - self.best_performance_state > 0
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
  0%|                                                                                                   | 0/100 [03:31<?, ?it/s, best loss: ?]
[2020-03-05 16:58:27,808] ERROR - scvi.inference.autotune.all | Caught ("unsupported operand type(s) for -: 'NoneType' and 'float'",) in auto_tune_scvi_model, starting cleanup.
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 144, in decorated
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 441, in auto_tune_scvi_model
    trials=trials,
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 407, in fmin
    rval.exhaust()
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 227, in run
    self.serial_evaluate()
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\base.py", line 844, in evaluate
    rval = self.fn(pyll_rval)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 165, in decorated
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 1237, in _objective_function
    trainer.train(**train_func_tunable_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 182, in train
    if not self.on_epoch_end():
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 230, in on_epoch_end
    self.history[save_best_state_metric + "_" + on][-1]
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 519, in update_state
    self.mode_save_state == "max" and scalar - self.best_performance_state > 0
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
[2020-03-05 16:58:27,811] INFO - scvi.inference.autotune.all | Cleaning up
[2020-03-05 16:58:27,812] DEBUG - scvi.inference.autotune.all | Cleaning up: closing files.
[2020-03-05 16:58:27,812] DEBUG - scvi.inference.autotune.all | Cleaning up: closing queues.
[2020-03-05 16:58:27,813] DEBUG - scvi.inference.autotune.all | Cleaning up: setting cleanup_event and joining threads.
[2020-03-05 16:58:27,814] DEBUG - scvi.inference.autotune.all | Cleaning up: terminating processes.
[2020-03-05 16:58:27,815] DEBUG - scvi.inference.autotune.all | Cleaning up: removing added logging handler.
[2020-03-05 16:58:27,816] DEBUG - scvi.inference.autotune.all | Cleaning up: removing autotune FileHandler.
Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 144, in decorated
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 441, in auto_tune_scvi_model
    trials=trials,
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 407, in fmin
    rval.exhaust()
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 227, in run
    self.serial_evaluate()
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperopt\base.py", line 844, in evaluate
    rval = self.fn(pyll_rval)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 165, in decorated
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\autotune.py", line 1237, in _objective_function
    trainer.train(**train_func_tunable_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 182, in train
    if not self.on_epoch_end():
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 230, in on_epoch_end
    self.history[save_best_state_metric + "_" + on][-1]
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\inference\trainer.py", line 519, in update_state
    self.mode_save_state == "max" and scalar - self.best_performance_state > 0
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by adamgayoso** [comment]
Could you try a different metric, like "elbo" as well as trying with `posterior_name="test_set"`? Autotune should really not be done with respect to the training set.

**Comment by pchiang5** [comment]
Turned out it was fine after I remove the arguments below. 

> 
> train_func_specific_kwargs={"n_epochs": n_epochs},
> max_evals=max_evals,
> trainer_specific_kwargs={
> "early_stopping_kwargs": {
> "early_stopping_metric": "entropy_batch_mixing",
> "save_best_state_metric": "entropy_batch_mixing",
> "patience": 20,
> "threshold": 0,
> "reduce_lr_on_plateau": True,
> "lr_patience": 10,
> "lr_factor": 0.2,
> }
> },

However, the trainer status still used "elbo" for early_stopping_metric. Is it fine runing this way? 

> trainer:
> {'early_stopping_kwargs': {'early_stopping_metric': 'elbo', 'save_best_state_metric': 'elbo', 'patience': 50, 'threshold': 0, 'reduce_lr_on_plateau': True, 'lr_patience': 25, 'lr_factor': 0.2}, 'metrics_to_monitor': ['elbo'], 'use_cuda': True, 'show_progbar': False, 'frequency': 1}

**Comment by pchiang5** [comment]
Turned out it was because I used 5 batches for the "entropy_batch_mixing" metric, which probably only allowed 2. When I used 2 batches, the issue was solved. 

Is there a way to perform the analysis with 5 batches?

Thanks.
