### ISSUE TITLE
KeyError: 'cmbc'

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#62]
Possibly stopped working after #54 ?

```
jeff@dean ~/git/scVI $ ./run_benchmarks.py --dataset cbmc
Traceback (most recent call last):
  File "./run_benchmarks.py", line 54, in <module>
    dataset = load_datasets(args.dataset, url=args.url)
  File "./run_benchmarks.py", line 22, in load_datasets
    gene_dataset = CiteSeqDataset('cmbc', save_path=save_path)
  File "/home/jeff/git/scVI/scvi/dataset/cite_seq.py", line 17, in __init__
    s = available_datasets[name]
KeyError: 'cmbc'
```

**Comment by imyiningliu** [comment]
There's a typo - should be `cbmc`. After merging the data loading PR, I'll fix it by directly calling `CbmcDataset`.
