### ISSUE TITLE
Workflow for cell classification

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#655]
I would like to classify 1 unlabeled dataset using 2 labeled reference datasets from different sources. Is the procedure below reasonable?

1. hyperparameter training with the space below.

```
space = {
    "model_tunable_kwargs": {"n_latent": hp.choice("n_latent", [6, 10, 15]), "n_layers": hp.choice("n_layers", [2, 3, 4]), "dropout_rate": hp.choice("dropout_rate", [0.1, 0.3, 0.5, 0.7, 0.9]),  "n_hidden": hp.choice("n_hidden", [64, 128, 256]), "reconstruction_loss": hp.choice("reconstruction_loss", [“zinb”, “nb”]), "dispersion": hp.choice("dispersion", ["gene", "gene-batch", "gene-label", "gene-cell"])},
	"trainer_tunable_kwargs": {"n_epochs_kl_warmup": hp.choice("n_epochs_kl_warmup", [None]), 'show_progbar': hp.choice('show_progbar', ["True"]), 'train_size': hp.choice('train_size', [0.1]},
	"train_func_tunable_kwargs": {"lr": hp.choice("lr", [0.0001, 0.001])},
}

```
2. unsupervised VAE training with the optimized parameters in #1.

3. classify the unlabeled cells with the VAE result above.

**Comment by adamgayoso** [comment]
Are you asking if your hyperparameter training choices are reasonable? I'm not sure 0.7 or 0.9 are worth the time to try for dropout_rate. I'd also try something like 25 latent dimensions, as well as one other KL warmup option.

**Comment by pchiang5** [comment]
Actually, I was asking if the workflow from step1 (hyperparameter training) ==> step2 (unsupervisedVAE) ==> step3 (SCANVI based on VAE at step2) is correct.  

I found the unsupervisedVAE step went through smoothly (code 1 below). However, an error message jumped out when I tried to load the VAE state below (code 2), even though the following SCANVI step could still run (code 3). Was that due to mismatched parameters between VAE and SCANVI?

As for the  "KL warmup option", did you mean "n_epochs_kl_warmup" or "n_iter_kl_warmup"?  What would be a good range to start with if I have 2-5 datasets with 8000-40000 cells in each dataset? Thanks.


Code 1
```

>>> n_epochs=10
>>> vae = VAE(simulation_1.nb_genes, n_batch=simulation_1.n_batches, n_labels=simulation_1.n_labels,
...           n_hidden=128, n_latent=8, n_layers=2, dispersion="gene-batch", dropout_rate=0.1, reconstruction_loss="zinb")
>>>
>>> trainer = UnsupervisedTrainer(vae, simulation_1, n_epochs_kl_warmup=None, train_size=1.0)
>>> trainer.train(n_epochs=20)
```

> 
> [2020-04-13 11:38:52,043] INFO - scvi.inference.inference | Training without KL warmup
> training: 100%|███████████████████████████████████████████████████████████████████████| 20/20 [23:18<00:00, 69.94s/it]
> 
> 

Code 2


```
>>> scanvi = SCANVI(simulation_1.nb_genes, simulation_1.n_batches, simulation_1.n_labels, n_layers=2)
>>> scanvi.load_state_dict(trainer.model.state_dict(), strict=False)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\ProgramData\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 845, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for SCANVI:
>         size mismatch for px_r: copying a param with shape torch.Size([21117, 2]) from checkpoint, the shape in current model is torch.Size([21117]).
>         size mismatch for z_encoder.mean_encoder.weight: copying a param with shape torch.Size([8, 128]) from checkpoint, the shape in current model is torch.Size([10, 128]).
>         size mismatch for z_encoder.mean_encoder.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([10]).
>         size mismatch for z_encoder.var_encoder.weight: copying a param with shape torch.Size([8, 128]) from checkpoint, the shape in current model is torch.Size([10, 128]).
>         size mismatch for z_encoder.var_encoder.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([10]).
>         size mismatch for decoder.px_decoder.fc_layers.Layer 0.0.weight: copying a param with shape torch.Size([128, 10]) from checkpoint, the shape in current model is torch.Size([128, 12]).

Code 3

```

>>> trainer_scanvi = SemiSupervisedTrainer(scanvi, simulation_1, classification_ratio=50,
... n_epochs_classifier=1, lr_classification=5 * 1e-3)
>>> trainer_scanvi.train(n_epochs=20)


```

> [2020-04-13 12:02:11,908] INFO - scvi.inference.inference | KL warmup phase exceeds overall training phaseIf your applications rely on the posterior quality, consider training for more epochs or reducing the kl warmup.
> [2020-04-13 12:02:11,909] INFO - scvi.inference.inference | KL warmup for 400 epochs
> training:  80%|████████████████████████████████████████████████████████              | 16/20 [31:22<07:51, 117.91s/it]
> 
> 
>

**Comment by adamgayoso** [comment]
Sorry, so you're asking if you can train the VAE and use the trained VAE for scANVI? I don't think that's possible, but I defer to @romain-lopez .

**Comment by romain-lopez** [comment]
I think we made it possible to do this type of workflow. @chenlingantelope is that a correct way to work with scANVI ?

**Comment by chenlingantelope** [comment]
Hi, yes it is possible to use a pretrained scVI model to train scanvi. 
`trainer_scanvi.model.load_state_dict(trainer.model.state_dict(), strict=False)`
here trainer_scanvi is the scANVI trainer, and trainer is the VAE model that has been pre-trained.
Hope this helps!

**Comment by pchiang5** [comment]
Hi @chenlingantelope 

Thank you for the information. I did try the: `trainer_scanvi.model.load_state_dict(trainer.model.state_dict(), strict=False)`

Somehow the loading failed with the following information: (Please see the Codes 1, 2, 3 in the quote for the complete process). How shall I address the issue?

> 
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\ProgramData\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 845, in load_state_dict
> self.class.name, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for SCANVI:
> size mismatch for px_r: copying a param with shape torch.Size([21117, 2]) from checkpoint, the shape in current model is torch.Size([21117]).
> size mismatch for z_encoder.mean_encoder.weight: copying a param with shape torch.Size([8, 128]) from checkpoint, the shape in current model is torch.Size([10, 128]).
> size mismatch for z_encoder.mean_encoder.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([10]).
> size mismatch for z_encoder.var_encoder.weight: copying a param with shape torch.Size([8, 128]) from checkpoint, the shape in current model is torch.Size([10, 128]).
> size mismatch for z_encoder.var_encoder.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([10]).
> size mismatch for decoder.px_decoder.fc_layers.Layer 0.0.weight: copying a param with shape torch.Size([128, 10]) from checkpoint, the shape in current model is torch.Size([128, 12]).


===============================================================
 
> Actually, I was asking if the workflow from step1 (hyperparameter training) ==> step2 (unsupervisedVAE) ==> step3 (SCANVI based on VAE at step2) is correct.
> 
> I found the unsupervisedVAE step went through smoothly (code 1 below). However, an error message jumped out when I tried to load the VAE state below (code 2), even though the following SCANVI step could still run (code 3). Was that due to mismatched parameters between VAE and SCANVI?
> 
> As for the "KL warmup option", did you mean "n_epochs_kl_warmup" or "n_iter_kl_warmup"? What would be a good range to start with if I have 2-5 datasets with 8000-40000 cells in each dataset? Thanks.
> 
> Code 1
> 
> ```
> 
> >>> n_epochs=10
> >>> vae = VAE(simulation_1.nb_genes, n_batch=simulation_1.n_batches, n_labels=simulation_1.n_labels,
> ...           n_hidden=128, n_latent=8, n_layers=2, dispersion="gene-batch", dropout_rate=0.1, reconstruction_loss="zinb")
> >>>
> >>> trainer = UnsupervisedTrainer(vae, simulation_1, n_epochs_kl_warmup=None, train_size=1.0)
> >>> trainer.train(n_epochs=20)
> ```
> 
> > [2020-04-13 11:38:52,043] INFO - scvi.inference.inference | Training without KL warmup
> > training: 100%|███████████████████████████████████████████████████████████████████████| 20/20 [23:18<00:00, 69.94s/it]
> 
> Code 2
> 
> ```
> >>> scanvi = SCANVI(simulation_1.nb_genes, simulation_1.n_batches, simulation_1.n_labels, n_layers=2)
> >>> scanvi.load_state_dict(trainer.model.state_dict(), strict=False)
> ```
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "C:\ProgramData\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 845, in load_state_dict
> > self.**class**.**name**, "\n\t".join(error_msgs)))
> > RuntimeError: Error(s) in loading state_dict for SCANVI:
> > size mismatch for px_r: copying a param with shape torch.Size([21117, 2]) from checkpoint, the shape in current model is torch.Size([21117]).
> > size mismatch for z_encoder.mean_encoder.weight: copying a param with shape torch.Size([8, 128]) from checkpoint, the shape in current model is torch.Size([10, 128]).
> > size mismatch for z_encoder.mean_encoder.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([10]).
> > size mismatch for z_encoder.var_encoder.weight: copying a param with shape torch.Size([8, 128]) from checkpoint, the shape in current model is torch.Size([10, 128]).
> > size mismatch for z_encoder.var_encoder.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([10]).
> > size mismatch for decoder.px_decoder.fc_layers.Layer 0.0.weight: copying a param with shape torch.Size([128, 10]) from checkpoint, the shape in current model is torch.Size([128, 12]).
> 
> Code 3
> 
> ```
> 
> >>> trainer_scanvi = SemiSupervisedTrainer(scanvi, simulation_1, classification_ratio=50,
> ... n_epochs_classifier=1, lr_classification=5 * 1e-3)
> >>> trainer_scanvi.train(n_epochs=20)
> ```
> 
> > [2020-04-13 12:02:11,908] INFO - scvi.inference.inference | KL warmup phase exceeds overall training phaseIf your applications rely on the posterior quality, consider training for more epochs or reducing the kl warmup.
> > [2020-04-13 12:02:11,909] INFO - scvi.inference.inference | KL warmup for 400 epochs
> > training: 100%|██████████████████████████████████████████████████████████████████████| 20/20 [39:09<00:00, 117.45s/it]
> > [2020-04-13 12:41:20,978] INFO - scvi.inference.inference | Training is still in warming up phase. If your applications rely on the posterior quality, consider training for more epochs or reducing the kl warmup.

**Comment by adamgayoso** [comment]
I think your issue is related to scanvi not being initialized with the same architecture (n_latent, n_layers) as was used in scvi, but not 100% sure.

**Comment by adamgayoso** [comment]
Closing due to inactivity.
