### ISSUE TITLE
Using entropy_batch_mixing in auto_tune_scvi_model raises TypeError: ufunc 'isnan' not supported for the input types

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/scVI#739]
When I use auto_tune_scvi_model with entropy_batch_mixing as metric_name I get the below error. This does not happen when I use marginal_ll. May be related to https://github.com/YosefLab/scVI/issues/610#issuecomment-595613470. I have 13 batches.
In my log I did not get https://github.com/YosefLab/scVI/blob/54faf80ebadf9294b246b845ac1835278f32a953/scvi/inference/posterior_utils.py#L132 It would have been nice if this was enabled for more batches.

Code: (I did not add full code, e.g. leaving out path variable, imports, data preparation,  ...)
```python
test_mode=False
metric_name="entropy_batch_mixing"

def if_not_test_else(x, y):
    if not test_mode:
        return x
    else:
        return y

n_epochs = if_not_test_else(int(400*20000/data.nb_cells), 1)
max_evals = if_not_test_else(100, 1)
reserve_timeout = if_not_test_else(180, 5)
fmin_timeout = if_not_test_else(300, 10)
use_cuda = True

space = {
            "model_tunable_kwargs": {
                "n_latent": 5 + hp.randint("n_latent", 16),  # [5, 20]
                "n_hidden": hp.choice("n_hidden", [64, 128, 256]),
                "n_layers": 1 + hp.randint("n_layers", 5),
                "dropout_rate": hp.choice("dropout_rate", [0.1, 0.3, 0.5, 0.7]),
                "reconstruction_loss": hp.choice("reconstruction_loss", ["zinb", "nb"]),
                "dispersion": hp.choice("dispersion", ["gene", "gene-batch"])
            },
            "train_func_tunable_kwargs": {
                "lr": hp.choice("lr", [0.01, 0.005, 0.001, 0.0005, 0.0001])
            },
        }

best_trainer, trials = auto_tune_scvi_model(
    gene_dataset=data,
    metric_name=metric_name,
    trainer_specific_kwargs ={'train_size':0.90,'use_cuda':use_cuda,
                              'n_epochs_kl_warmup':None,'n_iter_kl_warmup':int(128*5000/400)},
    train_func_specific_kwargs={"n_epochs": n_epochs},
    space=space,
    max_evals=max_evals,
    save_path=path_out_run,
    use_batches=True,
    # MongoDB is not availiable - cant use paralel
    parallel=False,
    #n_workers_per_gpu=4,
    reserve_timeout=reserve_timeout,
    fmin_timeout=fmin_timeout,
    exp_key="ref",
)
```

Error
```pytb
[2020-09-04 08:35:28,380] INFO - scvi.inference.autotune.all | Cleaning up
[2020-09-04 08:35:28,380] DEBUG - scvi.inference.autotune.all | Cleaning up: closing files.
[2020-09-04 08:35:28,380] DEBUG - scvi.inference.autotune.all | Cleaning up: closing queues.
[2020-09-04 08:35:28,380] DEBUG - scvi.inference.autotune.all | Cleaning up: setting cleanup_event and joining threads.
[2020-09-04 08:35:28,380] DEBUG - scvi.inference.autotune.all | Cleaning up: terminating processes.
[2020-09-04 08:35:28,380] DEBUG - scvi.inference.autotune.all | Cleaning up: removing added logging handler.
[2020-09-04 08:35:28,380] DEBUG - scvi.inference.autotune.all | Cleaning up: removing autotune FileHandler.
Traceback (most recent call last):
  File "/storage/groups/ml01/workspace/karin.hrovatin//code/diabetes_analysis/integration/scVI/1_run_ref_hyperopt_script.py", line 88, in <module>
    best_trainer, trials = auto_tune_scvi_model(
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/scvi/inference/autotune.py", line 145, in decorated
    return func(*args, **kwargs)
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/scvi/inference/autotune.py", line 478, in auto_tune_scvi_model
    _ = fmin(
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/fmin.py", line 379, in fmin
    return trials.fmin(
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/base.py", line 630, in fmin
    return fmin(
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/fmin.py", line 407, in fmin
    rval.exhaust()
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/fmin.py", line 227, in run
    self.serial_evaluate()
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/hyperopt/base.py", line 844, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/scvi/inference/autotune.py", line 167, in decorated
    return func(*args, **kwargs)
  File "/home/icb/karin.hrovatin/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/scvi/inference/autotune.py", line 1439, in _objective_function
    if np.isnan(loss):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

#### Versions:

0.6.6

**Comment by adamgayoso** [comment]
Hello,

Indeed, the entropy batch mixing is not implemented for more than 2 batches. I would also check that the number of batches is properly recorded in the dataset object.

Finally, we are actually removing the ability to use this metric in 1.0, though you should be able to write a custom hyperopt objective, which is explained in our tutorial.

**Comment by Hrovatin** [comment]
Why are you removing this metric? Is it not good?

**Comment by adamgayoso** [comment]
So it's not clear that optimizing for good mixing will lead to good preservation of the underlying biology, as the mixing can be optimized by randomly projecting the data. This is why we are removing it; that said, it is still possible to write a custom hyperopt objective doing this.

**Comment by Hrovatin** [comment]
Thank you.
